[0.000000] (-) TimerEvent: {}
[0.001165] (ball_chase) JobQueued: {'identifier': 'ball_chase', 'dependencies': OrderedDict()}
[0.001683] (ball_chase) JobStarted: {'identifier': 'ball_chase'}
[0.099695] (-) TimerEvent: {}
[0.200811] (-) TimerEvent: {}
[0.306364] (-) TimerEvent: {}
[0.411626] (-) TimerEvent: {}
[0.512256] (-) TimerEvent: {}
[0.612979] (-) TimerEvent: {}
[0.713866] (-) TimerEvent: {}
[0.816514] (-) TimerEvent: {}
[0.920157] (-) TimerEvent: {}
[1.021135] (-) TimerEvent: {}
[1.122042] (-) TimerEvent: {}
[1.176467] (ball_chase) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_parallel_executor/executor/parallel.py", line 75, in execute\n    loop.run_until_complete(future)\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete\n    self.run_forever()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever\n    self._run_once()\n  File "/usr/lib/python3.10/asyncio/base_events.py", line 1871, in _run_once\n    event_list = self._selector.select(timeout)\n  File "/usr/lib/python3.10/selectors.py", line 469, in select\n    fd_event_list = self._selector.poll(timeout, max_ev)\nKeyboardInterrupt\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 102, in build\n    return await extension.build(additional_hooks=additional_hooks)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 96, in build\n    available_commands = await self._get_available_commands(\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/build.py", line 194, in _get_available_commands\n    output = await check_output(\n  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 129, in check_output\n    assert not rc, f\'Expected {args} to pass: {stderr_data}\'\nAssertionError: Expected [\'/usr/bin/python3\', \'-W\', \'ignore:setup.py install is deprecated\', \'-W\', \'ignore:easy_install command is deprecated\', \'setup.py\', \'--help-commands\'] to pass: Fatal Python error: init_import_site: Failed to import the site module\nPython runtime state: initialized\nTraceback (most recent call last):\n  File "/usr/lib/python3.10/site.py", line 636, in <module>\n    main()\n  File "/usr/lib/python3.10/site.py", line 622, in main\n    known_paths = addusersitepackages(known_paths)\n  File "/usr/lib/python3.10/site.py", line 349, in addusersitepackages\n    addsitedir(user_site, known_paths)\n  File "/usr/lib/python3.10/site.py", line 232, in addsitedir\n    addpackage(sitedir, name, known_paths)\n  File "/usr/lib/python3.10/site.py", line 192, in addpackage\n    exec(line)\n  File "<string>", line 1, in <module>\nKeyboardInterrupt\n\n'}
[1.180582] (ball_chase) JobEnded: {'identifier': 'ball_chase', 'rc': 'SIGINT'}
[1.191217] (-) EventReactorShutdown: {}
